# Generated by Django 4.1.3 on 2022-12-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=50)),
                ('esal', models.IntegerField()),
                ('edesig', models.CharField(max_length=40)),
                ('eexp', models.IntegerField()),
            ],
        ),
    ]
