# Generated by Django 4.1.5 on 2023-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emart',
            name='PPP',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emart',
            name='TC',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
