# Generated by Django 4.1.5 on 2023-02-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_emart_ppp_alter_emart_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emart',
            name='TNOP',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
