# Generated by Django 4.1.5 on 2023-02-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_emart_tnop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emart_GST_NO', models.CharField(default='141FA08121FA081', max_length=15)),
                ('BILL_NO', models.IntegerField()),
                ('CUSTOMER_NAME', models.CharField(max_length=50)),
                ('MOBILE_NO', models.IntegerField()),
                ('PRODUCT_LIST', models.CharField(max_length=50)),
                ('PRODUCT_PRICE', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
