# Generated by Django 4.1.5 on 2023-02-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='DATE_TIME',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='PRODUCT_LIST',
            field=models.CharField(choices=[('santoor', 'santoor'), ('xxx soap', 'xxx soap'), ('TIDE', 'TIDE')], max_length=50),
        ),
    ]
