# Generated by Django 4.1.5 on 2023-02-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bill_date_time_alter_bill_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='PRODUCT_LIST',
            field=models.CharField(max_length=50),
        ),
    ]
