# Generated by Django 4.1.5 on 2023-02-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_bill_product_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='DATE_TIME',
        ),
    ]
