# Generated by Django 4.1.5 on 2023-02-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_bill_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='DATE_TIME',
            field=models.DateTimeField(null=True),
        ),
    ]
