# Generated by Django 4.1.5 on 2023-02-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bill_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='MOBILE_NO',
            field=models.CharField(max_length=50),
        ),
    ]
