# Generated by Django 4.1.5 on 2023-02-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_bill_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='PRODUCT_PRICE',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
