# Generated by Django 4.1.5 on 2023-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardingPoint', models.CharField(choices=[('Rajahmundry', 'Rajahmundry'), ('Vijayawada', 'Vijayawada'), ('Visakhapatnam', 'Visakhapatnam'), ('Hyderabad', 'Hyderabad'), ('Jangareddygudem', 'Jangareddygudem')], default='Rajahmundry', max_length=100)),
                ('DestinationPoint', models.CharField(choices=[('Rajahmundry', 'Rajahmundry'), ('Vijayawada', 'Vijayawada'), ('Visakhapatnam', 'Visakhapatnam'), ('Hyderabad', 'Hyderabad'), ('Jangareddygudem', 'Jangareddygudem')], default='Hyderabad', max_length=100)),
                ('NoofPassengers', models.IntegerField()),
                ('PassengerName', models.CharField(max_length=100)),
                ('PassengerAge', models.IntegerField()),
                ('Category', models.CharField(choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD')], max_length=50, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('ServiceCategory', models.CharField(choices=[('SUPER LUXURY', 'SUPER LUXURY'), ('SUPER DELUXE', 'SUPER DELUXE')], max_length=50, null=True)),
                ('DepartOn', models.DateField(null=True)),
                ('ArrivalOn', models.DateField(null=True)),
                ('Status', models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('PENDING', 'PENDING')], max_length=50)),
            ],
        ),
    ]
