# Generated by Django 4.1.5 on 2023-02-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='SeatNo',
            field=models.CharField(choices=[('01 w', '01 w'), ('02', '02'), ('03 w', '03 w'), ('04 w', '04 w'), ('05', '05'), ('06', '06'), ('07 w', '07 w'), ('08 w', '08 w'), ('09', '09'), ('10', '10'), ('11 w', '11 w'), ('12 w', '12 w'), ('13', '13'), ('14', '14'), ('15 w', '15 w'), ('16 w', '16 w'), ('17', '17'), ('18', '18'), ('19 w', '19 w'), ('20 w', '20 w'), ('21', '21'), ('22', '22'), ('23 w', '23 w'), ('24 w', '24 w'), ('25', '25'), ('26', '26'), ('27 w', '27 w'), ('28 w', '28 w'), ('29', '29'), ('30', '30'), ('31 w', '31 w'), ('32 w', '32 w'), ('33', '33'), ('34', '34'), ('35', '35'), ('36 w', '36 w')], max_length=50, null=True),
        ),
    ]
