# Generated by Django 4.1.5 on 2023-02-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dmart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DCGST_NO', models.CharField(max_length=15)),
                ('DBILL_NO', models.CharField(max_length=15)),
                ('PURCHASE_DT', models.DateTimeField()),
                ('DEALER_NAME', models.CharField(max_length=50)),
                ('PHONE_NUMBER', models.CharField(max_length=13)),
                ('PRODUCT_NAME', models.CharField(max_length=50)),
                ('TNOP', models.IntegerField()),
                ('PPP', models.DecimalField(decimal_places=10, max_digits=20)),
                ('TC', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
        ),
    ]
